setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS

unsetopt HIST_VERIFY

export HISTSIZE=5500
export SAVEHIST=5500
export HISTFILE=~/.zhistory